### ISSUE TITLE
Room Assistant

### ISSUE THREAD

**Issue by townsmcp** [B-Hartley/bruces_homeassistant_config#51]
@B-Hartley hey. Did you ever get room assistant to work well in the end? I got an RPI zero 2 delivered a couple of days ago, followed the RA website instructions and have it running with BLE as well as Bluetooth Classic. BT Classic seems rubbish and BLE is better but not great

**Comment by B-Hartley** [comment]
I've given up on it for the time being. 
I got it working. But not reliably. Pi zeros would drop off the network. 
Locations wouldn't be as accurate as I would like. 
I didn't have the time to spend on it. So I've shelved it for now. 

Shame.
